### ISSUE TITLE
Refactor list

### ISSUE THREAD

**Issue by jangko** [status-im/nim-toml-serialization#12]
- [x] remove `lex.push` and use more `inputStream.peek`.
- [ ] replace `toHex` with no alloc version.
- [ ] replace `intToStr` with no alloc version.
- [ ] replace `$` with no alloc version.
- [x] replace TomlTime.subsecond parser with no alloc version.
- [x] replace key normalization with no alloc version.

**Comment by zah** [comment]
I assume that by "no alloc" you mean the APIs provided by FastStreams (e.g. `faststreams/textio`)?

**Comment by jangko** [comment]
if `textio` could meet  toml requirements such as generating certain amount of leading zeros for integer/hex number, I will happily use it.
