### ISSUE TITLE
loadFile fails with: "template/generic instantiation from here"

### ISSUE THREAD

**Issue by firasuke** [status-im/nim-toml-serialization#90]
Hey there,

Thank you for your time and work on `toml_serialization`!

I am facing the following issue having upgraded to Nim 2.2.0, when using `Toml.loadFile`:

```nim
/home/firasuke/Downloads/Git/glaucus/rad/src/cerata.nim(40, 7) template/generic instantiation of `loadFile` from here
/home/firasuke/.nimble/pkgs2/toml_serialization-0.2.12-157d397bc26f9e9fad14a4bc7e2ca68a03e92a55/toml_serialization.nim(155, 13) template/generic instantiation of `readValue` from here
/home/firasuke/.nimble/pkgs2/serialization-0.2.2-320676ee66fba7dba2dc0f97bb2c73e1abbb1bf7/serialization.nim(31, 9) template/generic instantiation of `readValue` from here
/home/firasuke/.nimble/pkgs2/toml_serialization-0.2.12-157d397bc26f9e9fad14a4bc7e2ca68a03e92a55/toml_serialization/reader.nim(426, 8) template/generic instantiation of `decodeInlineTable` from
 here
/home/firasuke/.nimble/pkgs2/toml_serialization-0.2.12-157d397bc26f9e9fad14a4bc7e2ca68a03e92a55/toml_serialization/reader.nim(334, 25) template/generic instantiation of `parseInlineTableImpl`
from here
/home/firasuke/.nimble/pkgs2/serialization-0.2.2-320676ee66fba7dba2dc0f97bb2c73e1abbb1bf7/serialization/object_serialization.nim(215, 6) Error: [] must have some form of array type
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: rad
     Info:  Nimble data file "/home/firasuke/.nimble/nimbledata2.json" has been saved.
```

Any ideas what could be the issue here?

**Comment by jangko** [comment]
outdated nim-serialization?

**Comment by firasuke** [comment]
> outdated nim-serialization and nim-toml-serialization?

Oh I thought the latest version was `0.2.12`, no?

**Comment by jangko** [comment]
we not always increase the version number when new features or bugfixes are merged. including  changes because of new compiler version or other hotfixes. and because we only use nimble for CI and not for day to day development, we tend to manage our libraries using git commit hash rather than using version number.

**Comment by firasuke** [comment]
> we not always increase the version number when new features or bugfixes are merged. including changes because of new compiler version or other hotfixes. and because we only use nimble for CI and not for day to day development, we tend to manage our libraries using git commit hash rather than using version number.

oh I see, but I am still facing the same error even after running:

```
nimble install https://github.com/status-im/nim-toml-serialization@#master
```

(I have run `nimble clean` and `nimble uninstall` on the former cached versions of `toml_serialization`)

Could this be an issue with `nim-serialization` instead?

**Comment by firasuke** [comment]
And I did a reinstall of Nim 2.2.0 and this issue is gone.

I am closing this issue for now (and hopefully forever).

Thank you for your time!
